
let country_list = [
    "Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua & Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Angola",
    "Antarctica",
    "ArgentinaAS Samoa (American)",
    "Austria",
    "Australia",
    "Aruba",
    "Åland Islands",
    "Azerbaijan",
    "Bosnia & Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "St Barthelemy",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Caribbean NL",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cocos (Keeling) Islands",
    "Congo (Dem. Rep.)",
    "Central African Rep.",
    "Congo (Rep.)",
    "Switzerland",
    "Côte d'Ivoire",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cape Verde",
    "Curaçao",
    "Christmas Island",
    "Cyprus",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Western Sahara",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Micronesia",
    "Faroe Islands",
    "France",
    "Gabon",
    "Britain (UK)",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Equatorial Guinea",
    "Greece",
    "South Georgia & the South Sandwich Islands",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hong Kong",
    "Heard Island & McDonald Islands",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "British Indian Ocean Territory",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "St Kitts & Nevis",
    "Korea (North)",
    "Korea (South)",
    "Kuwait",
    "Cayman Islands",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "St Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Montenegro",
    "St Martin (French)",
    "Madagascar",
    "Marshall Islands",
    "North Macedonia",
    "Mali",
    "Myanmar (Burma)",
    "Mongolia",
    "Macau",
    "Northern Mariana Islands",
    "Martinique",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "St Pierre & Miquelon",
    "Pitcairn",
    "Puerto Rico",
    "Palestine",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Réunion",
    "Romania",
    "Serbia",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "St Helena",
    "Slovenia",
    "Svalbard & Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "South Sudan",
    "Sao Tome & Principe",
    "El Salvador",
    "St Maarten (Dutch)",
    "Syria",
    "Eswatini (Swaziland)",
    "Turks & Caicos Is",
    "Chad",
    "French Southern & Antarctic Lands",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "East Timor",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad & Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "US minor outlying islands",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vatican City",
    "St Vincent",
    "Venezuela",
    "Virgin Islands (UK)",
    "Virgin Islands (US)",
    "Vietnam",
    "Vanuatu",
    "Wallis & Futuna",
    "Samoa (western)",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe"
];

let country_prefix = [
    "AD","AE","AF","AG","AI","AL","AM","AO","AQ","AR",
    "AT","AU","AW","AX","AZ","BA","BB","BD","BE","BF",
    "BG","BH","BI","BJ","BL","BM","BN","BO","BQ","BR",
    "BS","BT","BV","BW","BY","BZ","CA","CC","CD","CF",
    "CG","CH","CI","CK","CL","CM","CN","CO","CR","CU",
    "CV","CW","CX","CY","CZ","DE","DJ","DK","DM","DO",
    "DZ","EC","EE","EG","EH","ER","ES","ET","FI","FJ",
    "FK","FM","FO","FR","GA","GB","GD","GE","GF","GG",
    "GH","GI","GL","GM","GN","GP","GQ","GR","GS","GT",
    "GU","GW","GY","HK","HM","HN","HR","HT","HU","ID",
    "IE","IL","IM","IN","IO","IQ","IR","IS","IT","JE",
    "JM","JO","JP","KE","KG","KH","KI","KM","KN","KP",
    "KR","KW","KY","KZ","LA","LB","LC","LI","LK","LR",
    "LS","LT","LU","LV","LY","MA","MC","MD","ME","MF",
    "MG","MH","MK","ML","MM","MN","MO","MP","MQ","MR",
    "MS","MT","MU","MV","MW","MX","MY","MZ","NA","NC",
    "NE","NF","NG","NI","NL","NO","NP","NR","NU","NZ",
    "OM","PA","PE","PF","PG","PH","PK","PL","PM","PN",
    "PR","PS","PT","PW","PY","QA","RE","RO","RS","RU",
    "RW","SA","SB","SC","SD","SE","SG","SH","SI","SJ",
    "SK","SL","SM","SN","SO","SR","SS","ST","SV","SX",
    "SY","SZ","TC","TD","TF","TG","TH","TJ","TK","TL",
    "TM","TN","TO","TR","TT","TV","TW","TZ","UA","UG",
    "UM","US","UY","UZ","VA","VC","VE","VG","VI","VN",
    "VU","WF","WS","YE","YT","ZA","ZM","ZW"
];

fm_country.text(country_list);

